apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: r4l11n2km-nodejs 
  janus-idp.io/tekton: r4l11n2km-nodejs
  backstage.io/kubernetes-id: r4l11n2km-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: r4l11n2km-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml